services:
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - instatags-net

  ai-service:
    build:
      context: .
      dockerfile: services/ai-service/Dockerfile
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - instatags-net
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ai-service
    environment:
      - AI_SERVICE_ADDR=ai-service:50051
      - GATEWAY_PORT=:8000
    networks:
      - instatags-net

networks:
  instatags-net:
      driver: bridge