// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: protos/ai/ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_protos_ai_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_protos_ai_ai_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashtags      []string               `protobuf:"bytes,1,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_protos_ai_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ai_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_protos_ai_ai_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetHashtags() []string {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

var File_protos_ai_ai_proto protoreflect.FileDescriptor

const file_protos_ai_ai_proto_rawDesc = "" +
	"\n" +
	"\x12protos/ai/ai.proto\x12\x02ai\"/\n" +
	"\x0ePredictRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\"-\n" +
	"\x0fPredictResponse\x12\x1a\n" +
	"\bhashtags\x18\x01 \x03(\tR\bhashtags2G\n" +
	"\tAIService\x12:\n" +
	"\x0fPredictHashtags\x12\x12.ai.PredictRequest\x1a\x13.ai.PredictResponseB0Z.github.com/sanguine59/img-getter-chrome-ext/aib\x06proto3"

var (
	file_protos_ai_ai_proto_rawDescOnce sync.Once
	file_protos_ai_ai_proto_rawDescData []byte
)

func file_protos_ai_ai_proto_rawDescGZIP() []byte {
	file_protos_ai_ai_proto_rawDescOnce.Do(func() {
		file_protos_ai_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_ai_ai_proto_rawDesc), len(file_protos_ai_ai_proto_rawDesc)))
	})
	return file_protos_ai_ai_proto_rawDescData
}

var file_protos_ai_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_ai_ai_proto_goTypes = []any{
	(*PredictRequest)(nil),  // 0: ai.PredictRequest
	(*PredictResponse)(nil), // 1: ai.PredictResponse
}
var file_protos_ai_ai_proto_depIdxs = []int32{
	0, // 0: ai.AIService.PredictHashtags:input_type -> ai.PredictRequest
	1, // 1: ai.AIService.PredictHashtags:output_type -> ai.PredictResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_ai_ai_proto_init() }
func file_protos_ai_ai_proto_init() {
	if File_protos_ai_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_ai_ai_proto_rawDesc), len(file_protos_ai_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_ai_ai_proto_goTypes,
		DependencyIndexes: file_protos_ai_ai_proto_depIdxs,
		MessageInfos:      file_protos_ai_ai_proto_msgTypes,
	}.Build()
	File_protos_ai_ai_proto = out.File
	file_protos_ai_ai_proto_goTypes = nil
	file_protos_ai_ai_proto_depIdxs = nil
}
